### ISSUE TITLE
Various warnings related to events

### ISSUE THREAD

**Issue by tsundokul** [sashetophizika/hyprscratch#3]
On hyprland 0.41.2+ds-1.1

```
An unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: workspacev2
An unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: movewindowv2
An unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: configreloaded
```

**Comment by sashetophizika** [comment]
Those are warnings from the `hyprland-rs` wrapper that I am using. Hyprland created new versions of basically all events and they are slowly migrating to them. You can ignore the warnings.

**Comment by tsundokul** [comment]
Yeah, I had some issues related to some types changes when serde de-serializing. Cool, thank you!
